NaverPayDev/pie

.changeset/tidy-shrimps-argue.md, packages/rollup/package.json, packages/rollup/src/index.ts, pnpm-lock.yaml
- #42
- react 17 esm 지원을 위해 rollup을 최신화합니다
-
=> [rollup] 의존성 최신화 및 react runtime classic으로 고정

.changeset/pink-pears-divide.md, .github/workflows/ci.yaml, packages/react-pdf/rollup.config.js, packages/rollup/generateRollupConfig.md, packages/rollup/src/index.ts
- #42
- react 관련 Rollup 설정을 하나로 합치고, README를 수정합니다
-
=> @naverpay/rollup react 옵션 수정

.changeset/famous-snakes-peel.md, packages/react-pdf/src/components/Pages.tsx
- #51
- pdf props 변경에 따라, 기존 pdf가 남아있지 않도록 수정합니다.
-
=> [react pdf] pdf props 변경에 따라, 기존 pdf가 남아있지 않도록 수정합니다.

packages/react-pdf/README.md, packages/react-pdf/개선사항.md
- this close #16
- 개선사항 및 장점 문서를 추가합니다.
-
=> [react pdf] 개선사항 및 장점 문서를 추가합니다.

.github/workflows/deploy-docs.yaml
- #62
- 테스트 브랜치로 설정이 되어 있었네욥..
=> [docs] main에 푸시될 때마다 워크플로우 실행되도록 합니다

.changeset/silver-games-try.md, packages/es-http-status-codes/package.json
- 누락된 sideEffects를 추가합니다
- @2-one-week 님.. 살려주세요.. ㅋㅋㅋ
=> :bug: 누락된 sideEffects를 추가합니다.

packages/es-http-status-codes/README.md
-
- README.md에 `es-` 전부 추가합니다.
- 혹시 npm 다시 배포 필요할까요..? https://www.npmjs.com/package/@naverpay/es-http-status-codes
=> [es-https-status-code] README.md에 es prefix 추가

.changeset/polite-guests-enjoy.md, packages/vanilla-store/README.md, packages/vanilla-store/jest.config.js, packages/vanilla-store/package.json, packages/vanilla-store/rollup.config.js, packages/vanilla-store/src/index.ts, packages/vanilla-store/src/persist/LocalStoragePersist.ts, packages/vanilla-store/src/persist/SessionStoragePersist.ts, packages/vanilla-store/src/persist/hooks.ts, packages/vanilla-store/src/persist/index.ts, packages/vanilla-store/src/persist/type.ts, packages/vanilla-store/src/react.test.ts, packages/vanilla-store/src/react.ts, packages/vanilla-store/src/shallowEqual.ts, packages/vanilla-store/src/store.test.ts, packages/vanilla-store/src/store.ts, packages/vanilla-store/stats.html, packages/vanilla-store/tsconfig.json, pnpm-lock.yaml
=> [WIP] vanilla store 이관

.changeset/pretty-comics-swim.md, packages/rollup/package.json, pnpm-lock.yaml
- #1
- 롤업 빌드시 `@naverpay/browserslist-config` 가 필요하기 때문에 devDeps 에서 deps 로 이동합니다.
-
=> [rollup] @naverpay/browserslist-config deps 이동

.github/workflows/release.yaml
-
- github token 에 npayfebot의 action token을 주입합니다
-
=> [공통] github token 에 npayfebot의 action token을 주입합니다

.github/workflows/release.yaml
-
- changeset 에서 push 등 github.token 사용하고 있는 게 있어, force push 도 주입한 토큰 사용할 수 있도록 수정합니다.
-
=> 👷 changeset 커밋 주체 변경

.github/workflows/release.yaml
-
- 커스텀한 액션과 조금 달라서 타 저장소에서 실험 마치고 왔습니다..
- PR: 체크아웃된 토큰으로 생성
- 커밋: GITHUB_TOKEN으로 생성
-
=> changeset 설정 수정

.github/workflows/release.yaml
-
- github user bot으로 셋팅되도록 수정
-
=> github user bot으로 셋팅되도록 수정

.github/workflows/detect-changed-packages.yml, .github/workflows/release.yaml
- #103 
- npay 의 detect add, publish 를 이용하도록 변경합니다
-
=> [공통] changeset action 을 npay changeset action 으로 이사

.github/workflows/release.yaml
- #103
- changesets action npm token setting 위치를 변경합니다.
-
=> [공통] changesets action npm token setting 위치를 변경합니다.

packages/vanilla-store/README.md
- #112
- @keemhyunseok 님 혹시 README에서 제거된 인터페이스가 보이는데 맞는지 확인 부탁드려도 될까요?? (`useSyncWithClientPersistStore`)
-
=> [vanilla-store] README.md v0.1.0 업데이트

.changeset/orange-pans-relax.md, package.json, packages/react-pdf/vite.config.mjs, packages/vanilla-store/vite.config.mjs, pnpm-lock.yaml
=> pite 2.0.0으로 pie를 빌드합니다

.changeset/strong-moments-repeat.md, packages/vanilla-store/README.md, packages/vanilla-store/package.json
- #133 
- 실험 버전이 끝났으므로 주석 제거
- 변경된 인터페이스 반영
- 누락된 peerDeps 추가
-
=> [vanilla-store] Update README.md & add react@19 to peerDeps

.changeset/shaggy-cities-taste.md, packages/react-pdf/CHANGELOG.md, packages/react-pdf/package.json
-   7336006: ✨ feat: add URL parsing polyfill to PdfViewer, AnnotationLayer, and pdf utilities
PR: [✨ feat: add URL parsing polyfill to PdfViewer, AnnotationLayer, and pdf utilities](https://github.com/NaverPayDev/pie/pull/144)
=> 🚀 version changed packages

.changeset/legal-rooms-stay.md, packages/react-pdf/package.json, packages/react-pdf/storybook/pdf-viewer.stories.tsx, packages/react-pdf/tsconfig.json
-
- [react-pdf] style export 
- pite 로 Migration하면서 style export 누락되어 스타일 적용이 안되었습니다. (pite는 style 기본 export)
-
=> [react-pdf] style export 

.github/workflows/rc.yml
- #152
- The same work as #153, except that it generates a release tag.
- I'll do the test on `@naverpay/vanilla-store` next patch
=> Added rc publish action

package.json, pnpm-lock.yaml
- #156 
- Override into a customized package that applies our own method, not the version bump method of peerDeps in common changesets. 
-
=> Overrides @changesets/assemble-release-plan in @changesets/cli

.changeset/moody-cars-drive.md, packages/utils/src/utils/maskPhoneNumber.ts
- #158 
- 지역번호 02로 시작하는 전화번호 마스킹 로직 추가하였습니다
- 리뷰해주시면 반영하겠습니다 🙇‍♂️ 
-
=> [#158] 지역번호 02 마스킹 처리 추가

packages/url-param-compressor/src/URLParamCompressor.test.ts
#166
- 테스트 코드 추가
@Ohjaeyeop 님,
- `compress` 메서드를 썼을 떄 압축이 되었는지, 안되었는지를 알아야 _cb=압축된 문자열 로 넘길지, 혹은 rurl, surl 등 기존 쿼리를 유지할지 판단할 수 있을 것 같습니다.
- `decompress` 는 압축 해제 실패시에 실패되었는지 쓰는 쪽에서 알아야 후속처리를 하던지 말던지? 할 수 있을 것 같습니다.
- 현재 제가 작성한 시나리오는 모든 쿼리를 압축하여 _cb=`압축된문자열` 로 넣는 상황을 가정한건데요. 이 테스트 코드를 실제 저희 페이비번 쪽 복잡한 시나리오에 대입해서 테스트 코드 작성 부탁드립니다. (홈 > 페이비번 > 음성키패드 > ARS인증....)
- `DeflateOptions` 옵션도 검토 부탁드립니다. 기본값이 있음 좋을거같고, 어떤 값이 적절할지 휴리스틱하게(?) 검토 부탁드립니다.
- `_cb=압축된문자열`을 넘길 떄 `압축된 문자열`을 encode  시도하는 사람들도 더러 있을 것 같은데요. 이게 필요 없다는걸 증명할 수 있는 방법이 있을까요?
- 벤치마크 테스트도 있음 좋을 것 같습니다 (극단적인 길이에서)
- 플레이라잇, 빌드매트릭스를 사용해서 최대한 다양한 환경에서 테스트 해주세요. 지금 그대로면 오픈소스로 나온 의미가 없을듯!@
- 분명히 이 문자열이 뭐일지 궁금해하는 사람들이 있을테니 온라인으로 테스트 할 수 있는 사이트를 만들어주세요.
- 모든 쿼리를 압축할지, 중복이 많은 문자열만 할지 고민해주세요.
> 싱싱미역상태라 잘못된 의견이 있을수도 있음
=> [#166] URLParamCompressor 테스트 케이스 추가 및 페이지 네비게이션 시나리오 구현

.github/workflows/node-matrix.yml
- #166 
- url-param-compressor > Node 18, 20, 22 환경에서 테스트
- Node 16은 호환되는 pnpm 버전을 설치해야 하는데 실패..
-
=> [url-param-compressor] build matrix 추가

.github/workflows/ci.yaml, .github/workflows/node-matrix.yml, .gitignore, packages/url-param-compressor/package.json, packages/url-param-compressor/playwright.config.mts, packages/url-param-compressor/tests/UrlParamCompressor.spec.ts, packages/url-param-compressor/vitest.config.mts, pnpm-lock.yaml
=> [url-param-compressor] 브라우저 환경 테스트 추가

package.json, packages/url-param-compressor/README.md, packages/url-param-compressor/package.json, packages/url-param-compressor/src/URLParamCompressor.bench.ts, packages/url-param-compressor/src/URLParamCompressor.ts, turbo.json
=> [url-param-compressor] bench 추가 /  jsdoc 작성

packages/url-param-compressor/README.md
=> [url-param-compressor] 압축 방식 Readme에 설명 추가
